@host=localhost:9001
@uuid=it-means-the-uuid-is-optional

// Create a new profile - 201 Created
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "MALE",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "leopold"
}

###


// Create a new profile with Uuid - 201 Created
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "FEMALE",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "leopold",
  "uuid": "{{uuid}}"
}

###


// Get a profile By Uuid - 200 OK
###
GET {{host}}/api/profiles/uuid?uuid={{uuid}}

###

@secretKey=DonaEmilyEatSteakLeopold
// Get All Profiles except contacts - 200 OK
###
GET {{host}}/api/profiles?secretKey={{secretKey}}

###


// Get a ramdom profile - 200 OK
###
GET {{host}}/api/profiles/random?uuid={{uuid}}&excludeProfiles=

###

// Suggest a nickname - 200 OK
###
POST {{host}}/api/profiles/nickname
Content-Type: application/json

{
  "description": [
    "나는 딸기를 좋아해",
    "나는 포도도 좋아해",
    "제일 좋아하는 음식은 치킨이야"
  ]
}
###
// Responses are cached
