@uuid=ec5ea893-8540-42c5-958a-ce69ed7f9f63

// Issue a verification code for uuid - 200 OK
###
POST {{host}}/api/viewers/verification
Content-Type: application/json

{
  "uuid": "{{uuid}}"
}

> {%
    client.global.set("verificationCode", response.body.result.verificationCode);
%}

###
// If the uuid is not registered, then a new verification code will be created.
// Otherwise the uuid is registered, then return the verification code for the uuid.


@secretKey=DonaEmilyEatSteakLeopold
// Verify the uuid with the verification code - 200 OK
###
POST {{host}}/api/viewers
Content-Type: application/json

{
  "secretKey": "{{secretKey}}",
  "verificationCode": {{verificationCode}},
  "ticket": 1
}

###

// Verify the uuid with the verification code - 200 OK

@deposit=5000
###
POST {{host}}/api/viewers/sms
Content-Type: application/json

{
  "secretKey": "{{secretKey}}",
  "message":"[Web발신]\n[카카오뱅크]\n남*현(3873)\n05\/14 11:30\n입금 {{deposit}}원\n{{verificationCode}}\n잔액 6원"
}

###
// The verification code is able to be used only once.


// sse for issued ticket
###
GET {{host}}/api/viewers/tickets/events?uuid={{uuid}}
Accept: text/event-stream

###

// sse for issued ticket
###
GET {{host}}/api/viewers/events
Accept: text/event-stream

###

// Get a Viewer by uuid - 200 OK
// with purchased profiles info
###
GET {{host}}/api/viewers/uuid?uuid={{uuid}}

###


// Get All Viewers - 200 OK
###
GET {{host}}/api/viewers?secretKey={{secretKey}}

###

@profileId=2
// ConsumeTicket - 200 OK
###
POST {{host}}/api/profiles/contact
Content-Type: application/json

{
  "uuid": "{{uuid}}",
  "profileId": {{profileId}}
}

###
// If this profile is already purchased, then does not consume tickets.


// Get a purchased profile - 200 OK
###
GET {{host}}/api/profiles/{{profileId}}?uuid={{uuid}}

###
