@uuid=26eaadba-a2a0-4de3-ae7c-ea98cd14a014

### Get development token (dev environment only)
POST {{host}}/api/auth/dev/token
Content-Type: application/json

{
  "uuid": "{{uuid}}",
  "accessKey": "{{accessKey}}"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### Expected Response:
# 200 OK
# {
#   "timestamp": "2025-04-27T12:16:55.043588+09:00",
#   "result": {
#     "uuid": "26eaadba-a2a0-4de3-ae7c-ea98cd14a014",
#     "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
#     "refreshToken": null
#   }
# }
