### Approve KakaoPay payment
POST {{host}}/api/viewers/payment/kakaopay/approve
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "pgToken": "SIMULATED_PG_TOKEN_12345",
  "orderId": ""
}
