### Approve KakaoPay payment
POST {{host}}/api/viewers/payment/kakaopay/approve
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "pgToken": "fd50ce6ad7dacdaf9f3f",
  "orderId": "1145ae95-5b54-48b3-9fc2-156201ffd71e_250901010928"
}
