### Create profile - Success case
POST {{host}}/api/profiles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "gender": "MALE",
  "department": "컴퓨터학부3",
  "birthYear": 2000,
  "animal": "DOG",
  "contact": "@myinstagram1",
  "school": "숭실대",
  "mbti": "INTJ",
  "nickname": "코딩하는강아지",
  "introSentences": [
    "개발을 좋아하는 3학년입니다",
    "주로 백엔드 개발을 합니다",
    "커피 마시면서 코딩하는 걸 좋아해요"
  ]
}

### Create profile without a School - Success case
POST {{host}}/api/profiles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "gender": "MALE",
  "department": "컴퓨터학부3",
  "birthYear": 2000,
  "animal": "DOG",
  "contact": "@myinstagram1",
  "mbti": "INTJ",
  "nickname": "코딩하는강아지",
  "introSentences": [
    "개발을 좋아하는 3학년입니다",
    "주로 백엔드 개발을 합니다",
    "커피 마시면서 코딩하는 걸 좋아해요"
  ]
}
