@host=localhost:8080

// When the gender is blank, return 400 Bad Request
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "nickname",
  "introSentences" : ["나는 딸기를 좋아해", "나는 포도도 좋아해", "제일 좋아하는 음식은 치킨이야"]
}

###

// When the animal is blank, return 400 Bad Request
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "MALE",
  "animal": "",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "nickname",
  "introSentences" : ["나는 딸기를 좋아해", "나는 포도도 좋아해", "제일 좋아하는 음식은 치킨이야"]
}

###

// When the contact is blank, return 400 Bad Request
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "MALE",
  "animal": "DOG",
  "contact": "",
  "mbti": "ISTJ",
  "nickname": "nickname",
  "introSentences" : ["나는 딸기를 좋아해", "나는 포도도 좋아해", "제일 좋아하는 음식은 치킨이야"]
}

###

// When the MBTI value is blank, return 400 Bad Request
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "MALE",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "",
  "nickname": "nickname",
  "introSentences" : ["나는 딸기를 좋아해", "나는 포도도 좋아해", "제일 좋아하는 음식은 치킨이야"]
}

###

// When the nickname exceeds the maximum length, return 400 Bad Request
###
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "FEMALE",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "Maximum length is 15",
  "introSentences" : ["나는 딸기를 좋아해", "나는 포도도 좋아해", "제일 좋아하는 음식은 치킨이야"]
}

###

// When any introSenteces exceeds the maximum length, return 400 Bad Request
POST {{host}}/api/profiles
Content-Type: application/json

{
  "gender": "FEMALE",
  "animal": "DOG",
  "contact": "@leo",
  "mbti": "ISTJ",
  "nickname": "nickname",
  "introSentences" : ["제일 좋아하는 음식은 치킨이야 제일 좋아하는 음식은 치킨이야 제일 좋아하는 음식은 치킨이야 제일 좋아하는 음식은 치킨이야"]
}
