### Get my profile
GET {{host}}/api/profiles/me
Authorization: Bearer {{accessToken}}

###

### Get purchased profile by ID
GET {{host}}/api/profiles/1
Authorization: Bearer {{accessToken}}

### Expected Response:
# 200 OK - If profile was purchased
# {
#   "timestamp": "2025-04-27T14:47:59.730735+09:00",
#   "result": {
#     "profileId": 1,
#     "gender": "FEMALE",
#     "department": "학과",
#     "birthYear": 2000,
#     "animal": "DOG",
#     "contact": "@leo",
#     "mbti": "ISTJ",
#     "nickname": "leopold",
#     "introSentences": [
#       "나는 딸기를 좋아해",
#       "나는 포도도 좋아해",
#       "제일 좋아하는 음식은 치킨이야"
#     ]
#   }
# }

### Error Cases:
# 403 Forbidden - Profile not purchased
# 404 Not Found - Profile doesn't exist