### Get random profile - Looking for FEMALE profiles
GET {{host}}/api/profiles/random?gender=FEMALE
Authorization: Bearer {{accessToken}}

###

### Get random profile with exclusions
GET {{host}}/api/profiles/random?gender=MALE&excludeProfiles=1,2,3
Authorization: Bearer {{accessToken}}

### Expected Response:
# 200 OK
# {
#   "timestamp": "2025-04-27T14:59:57.30334+09:00",
#   "result": {
#     "profileId": 4,
#     "gender": "MALE",
#     "department": "학과",
#     "birthYear": 2000,
#     "animal": "DOG",
#     "mbti": "ISTJ",
#     "nickname": "leopold",
#     "introSentences": [
#       "나는 딸기를 좋아해",
#       "나는 포도도 좋아해",
#       "제일 좋아하는 음식은 치킨이야"
#     ]
#   }
# }

### Error Cases:
# 404 Not Found - No random profiles available
# 404 Not Found - Viewer doesn't exist