### Add my profile to blacklist
POST {{host}}/api/blacklists/me
Authorization: Bearer {{accessToken}}

### Expected Response:
# 201 Created
# {
#   "timestamp": "2025-04-27T12:16:55.043588+09:00",
#   "result": {
#     "id": 1,
#     "profileId": 123
#   }
# }