### Add my profile to blacklist
POST {{host}}/api/blacklists/me
Authorization: Bearer {{accessToken}}

> {%
    client.test("Add my profile to blacklist", function() {
        client.assert(response.status === 201, "Response status is not 201");
        client.assert(response.body.result !== undefined, "Result is missing");
        client.assert(response.body.result.id !== undefined, "Blacklist id is missing");
        client.assert(response.body.result.profileId !== undefined, "Profile id is missing");
    });
%}

### Expected Response:
# 201 Created
# {
#   "timestamp": "2025-04-27T12:16:55.043588+09:00",
#   "result": {
#     "id": 1,
#     "profileId": 123
#   }
# }
