@host=localhost:8080
@uuid=ec5ea893-8540-42c5-958a-ce69ed7f9f63

// Issue a verification code for uuid - 400 Bad Request
###
POST {{host}}/api/viewers/verification
Content-Type: application/json

###
