// Issue a verification code for uuid - 200 OK
###
POST {{host}}/api/viewers/verification
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "referralCode": "test"
}

###
// If the uuid is not registered, then a new verification code will be created.
// Otherwise the uuid is registered, then return the verification code for the uuid.


@secretKey=DonaEmilyEatSteakLeopold
// Verify the uuid with the verification code - 200 OK
###
POST {{host}}/api/viewers
Content-Type: application/json

{
  "secretKey": "{{secretKey}}",
  "verificationCode": {{verificationCode}},
  "ticket": 3
}

###


// The verification code is able to be used only once. - 404 NOT FOUND
###
POST {{host}}/api/viewers
Content-Type: application/json

{
  "secretKey": "{{secretKey}}",
  "verificationCode": {{verificationCode}},
  "ticket": 3
}

###

// Issue a verification code for uuid - 200 OK
###
POST {{host}}/api/viewers/verification
Content-Type: application/json

{
  "uuid": "{{uuid}}"
}

###

// When Invalid secretKey, return 403 FORBIDDEN
###
POST {{host}}/api/viewers
Content-Type: application/json

{
  "secretKey": "invalidSecretKey",
  "verificationCode": {{verificationCode}},
  "ticket": 3
}

###

// When ticket is not a positive number, return 400 BAD REQUEST
###
POST {{host}}/api/viewers
Content-Type: application/json

{
  "secretKey": "{{secretKey}}",
  "verificationCode": {{verificationCode}},
  "ticket": 0
}

###