### Generate my referral code (default)
POST {{host}}/api/referrals
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "customCode": "test"
}

### Generate my referral code (custom)
POST {{host}}/api/referrals
Content-Type: application/json
Authorization: Bearer {{accessToken}}
