name: Test ECR Permissions

on:
  workflow_dispatch:

jobs:
  test-permissions:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-PermissionTest
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Test ECR Public Permissions
        env:
          ECR_REGISTRY: public.ecr.aws/${{ vars.ECR_PUBLIC_REGISTRY_ID }}
        run: |
          echo "=== ECR Public 권한 테스트 ==="
          echo "ECR_REGISTRY: $ECR_REGISTRY"
          
          # 1. GetAuthorizationToken 테스트
          echo "1. GetAuthorizationToken 테스트:"
          if aws ecr-public get-authorization-token --region us-east-1; then
            echo "✅ GetAuthorizationToken 성공"
          else
            echo "❌ GetAuthorizationToken 실패"
          fi
          
          # 2. Repository 존재 확인
          echo -e "\n2. Repository 존재 확인:"
          if aws ecr-public describe-repositories --region us-east-1 --repository-names yourssu/signal; then
            echo "✅ Repository yourssu/signal 존재"
          else
            echo "❌ Repository yourssu/signal 없음 또는 접근 권한 없음"
          fi
          
          # 3. 현재 IAM 정보 확인
          echo -e "\n3. 현재 IAM 정보:"
          aws sts get-caller-identity
          
          # 4. ECR Public 로그인 테스트 (이미 로그인됨)
          echo -e "\n4. ECR Public 로그인 상태:"
          echo "✅ ECR Public 로그인 완료 (단계에서 수행됨)"

      - name: Test Repository Access
        env:
          ECR_REGISTRY: public.ecr.aws/${{ vars.ECR_PUBLIC_REGISTRY_ID }}
        run: |
          echo "=== Repository 접근 테스트 ==="
          
          # Registry URL 구성
          FULL_REPO_PATH="$ECR_REGISTRY/yourssu/signal"
          
          echo "Registry: $ECR_REGISTRY"
          echo "Full path: $FULL_REPO_PATH"
          
          # Repository 태그 목록 확인
          echo -e "\n기존 태그 목록:"
          aws ecr-public describe-images --region us-east-1 --repository-name yourssu/signal --query 'imageDetails[*].imageTags' --output table || echo "태그 조회 실패 또는 이미지 없음"